### ISSUE TITLE
Integrate Interview experiences

### ISSUE THREAD

**Issue by pandusonu2** [RECursion-NITD/RECursionNITD-website#63]
https://github.com/RECursion-NITD/Interview-Questions

**Comment by vishvanath45** [comment]
Yes!, This plan is in pipeline. :D
Although the work will begin next sem.

**Comment by vishvanath45** [comment]
@ash1969 You wanna pickup on this?

lmk, there are few things to keep in mind, we can't make these publicly available.

**Comment by gcnit** [comment]
You cannot add company name in the website. I got a notice from one company
when the company name was public and that is when I had to make it private.

You can either make this available with company name only on login or
blacklist it for search engines through robots.txt

**Comment by vishvanath45** [comment]
@gcnit  Yes, I am aware of this thing, but now since we have User-authentication/Email-verification in place, a simple solution which we are planning to implement is to allow read access to users having email handle with `@{btech/mtech/phd}.nitdgp.ac.in` only. 

This will prevent interview experiences from getting indexed in search engine, thus avoid getting any public visibility, moreover it will automate the tedious task of formatting, uploading the Interview Exp on Facebook post.

**Comment by gcnit** [comment]
Do you mind whitelisting users on request given that we and our seniors don't have a nitdgp email address?

It would be great for me if I can get access as well.

**Comment by vishvanath45** [comment]
Sure, we can incorporate that as well.

Tagging webd team as well, just to keep this in their mind.

cc @vjs22334 @pkkp86nitd @ash1969 @kmAyush @piedpipr

**Comment by vjs22334** [comment]
wouldn't just restricting to logged in users be enough to prevent search engines from finding it?

**Comment by ash1969** [comment]
Interview Experiences has been integrated. This issue can be closed!

**Comment by pandusonu2** [comment]
Awesome :D
