### ISSUE TITLE
Remove unnecessary folders

### ISSUE THREAD

**Issue by naveenkumarsangi** [RECursion-NITD/RECursionNITD-website#66]
- `.idea`
- `website/env`
- `website/.vscode`

These shouldn't be committed to the repository. Please commit the removal of these folders and include these paths in the `.gitignore` file. 

And if you insist on using some sort of configuration sharing between text editors, you should rather use a `.editorconfig` file.

**Comment by vishvanath45** [comment]
Thanks for reporting the Issue, this has been fixed in #69 and merged in `recursion:testing`, it will be reflected in `master` when we update it with `testing`.

Commit authored by : @PiedPiPr  

@nkprince007, I am closing the issue now, as this has been fixed, feel free to reopen if you would like to suggest some modifications.
