### ISSUE TITLE
Create event inputs need to be well-defined

### ISSUE THREAD

**Issue by kmAyush** [RECursion-NITD/RECursionNITD-website#93]
Creating an event using [Create Event Link](https://recursionnitd.in/events/create/) is bit complex as input for start time and end time format is not defined. 

Possible solution - 
1. Taking input for date and time in separate fields.
2. Providing a format for start time and end time input.

![Screenshot from 2019-11-08 19-46-05](https://user-images.githubusercontent.com/36049076/68483334-5cc94900-0261-11ea-9288-59a9e18d45d6.png)

**Comment by arin17bishwa** [comment]
Working on it bhaiya.

Already implemented a Datetime picker for start_time and end_time.

But there were some more problems regarding URL namespacing, resolving them now.

**Comment by arin17bishwa** [comment]
The current way images are saved requires us to have the event's ID value added to the image filename.
 But we can't have the ID value before saving the object. So is it all right if I use something like str(datetime.now()).replace('.','-') instead of using str(id) [previously it was calling the string format of id() function]

**Comment by iamskab** [comment]
Completed !
